/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux wc8782-1997 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Tue Apr  4 13:39:53 CST 2023"
#define BUILD_ENV_SRCDIR "/home/wangcan/workspace/samba-3.6.23/source3"
#define BUILD_ENV_BUILDDIR "/home/wangcan/workspace/samba-3.6.23/source3"
#define BUILD_ENV_USER "wangcan"
#define BUILD_ENV_HOST "wc8782-1997"
#define BUILD_ENV_COMPILER "aarch64-unknown-nto-qnx7.0.0-gcc"
#endif /* _BUILD_ENV_H */
