
modify_date="2023/11/06"
default_parse_version="2.0.1"

[i30_network]
listen_ip="172.168.17.2"
listen_port=30
upload_ip="172.168.2.3"
upload_port=39
upload_connect_timeout_ms=3000
upload_connect_retry_max=6

[objective_network]
listen_ip="183.13.14.1"
listen_port=72

[log]
level=3
root_path="xxx"
testbed_stdout_name="testbed_stdout"
server_stdout_name="server_stdout"

## xjf add new 2024/04/02, for set mv operation for testbed when testbed be loaded
[[mv_testbed_file]]
relative_to_testbed_root_path="./libarcsoft_vehicle_utils_skel.so"
target_device_dst_file_path="/etc/images/dsp/libarcsoft_vehicle_utils_skel.so"
[[mv_testbed_file]]
relative_to_testbed_root_path="./libneat_1_1_skel.so"
target_device_dst_file_path="/etc/images/dsp/libneat_1_1_skel.so"

[cache]
tmp_root_dir_path="xxx"
i30_root_dir_path="xxx"
objective_root_dir_path="xxx"


[objective_runtime]
objective_run_testbed_process_max=3
objective_download_thread_max=3
objective_upload_thread_max=3
objective_cache_video_max=4